services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - db
  db:
    volumes:
      - program_db:/data/db
    image: mongo:latest
    ports:
      - "27017:27017"
volumes:
   program_db: